name: flutter_auto_form
description: A package simplifying the process of creating user friendly forms in Flutter
version: 1.0.2
homepage: https://github.com/GaspardMerten/flutter_auto_form
publish_to: 'none'

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  file_picker: ^4.1.6
  smarter_text_field: ^0.0.7
  date_field:
    path: ../date_field
  dropdown_search: ^5.0.3

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
