name: flutter_auto_form
description: A package simplifying the process of creating user friendly forms in Flutter
version: 1.0.1
homepage: https://github.com/GaspardMerten/flutter_auto_form

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  smarter_text_field: ^0.0.7
  date_field: ^3.0.2
  dropdown_search: ^5.0.3

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
