name: flutter_auto_form
description: A package simplifying the process of creating user friendly forms in Flutter
version: 1.0.7
homepage: https://github.com/GaspardMerten/flutter_auto_form

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  file_picker: ^4.6.1
  smarter_text_field: ^0.0.7
  date_field: ^3.0.5
  dropdown_search: ^5.0.6

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1



analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - lib/**.g.dart
    - lib/**.inject.dart
    - lib/**.inject.summary
    - test/**.g.dart
    - test/**.inject.dart
