name: flutter_auto_form
description: A package simplifying the process of creating user friendly forms in Flutter
version: 0.0.2
homepage: https://github.com/GaspardMerten/flutter_auto_form

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
